src/objects/Auction__c.object
<CustomObject>
    <description>The master object which is the parent of all campaigns and auction items, that represent the entire auction.</description>
    <fields>
        <fullName>Auction_Date__c</fullName>
        <label>Auction Date</label>
        <type>Date</type>
    </fields>
    <label>Auction</label>
    <nameField>
        <label>Auction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Auctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Auction_Item__c.object
<CustomObject>
    <description>A purchaseable item at an auction, such as a weekend getaway, a food basket, a certificate for free exercise classes.</description>
    <fields>
        <fullName>Auction_Item_Name__c</fullName>
        <inlineHelpText>The short name for the auction item.</inlineHelpText>
        <label>Auction Item Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Auction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The auction this item is for.</inlineHelpText>
        <label>Auction</label>
        <referenceTo>Auction__c</referenceTo>
        <relationshipLabel>Auction Items</relationshipLabel>
        <relationshipName>Auction_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FMV_Override__c</fullName>
        <inlineHelpText>If empty, the sum of the Actual FMV&apos;s of all pieces will be used.</inlineHelpText>
        <label>FMV Override</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Auction Item</label>
    <nameField>
        <label>Auction Item ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Auction Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Auction_Campaign_Type__c</fullName>
        <label>Auction Campaign Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Auction Attendees</fullName>
                </value>
                <value>
                    <fullName>Auction Tickets</fullName>
                </value>
                <value>
                    <fullName>Auction Sponsors</fullName>
                </value>
                <value>
                    <fullName>Auction Item Donors</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Auction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The auction this campaign is a part of.</inlineHelpText>
        <label>Auction</label>
        <referenceTo>Auction__c</referenceTo>
        <relationshipLabel>Campaigns</relationshipLabel>
        <relationshipName>Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Campaign</fullName>
        <active>true</active>
        <description>default record type required to enable installation of Auctions package</description>
        <label>Campaign</label>
    </recordTypes>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Auction_Deductible_Amount__c</fullName>
        <formula>IF ( 
OR ( NOT( $RecordType.Name = &quot;Purchase&quot; ), NOT ( $RecordType.Name = &quot;TBD&quot; ) ) ,
IF(Amount &gt; Auction_Non_Deductible_Amount__c , Amount - Auction_Non_Deductible_Amount__c , 0),
0
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Auction Deductible Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Auction_Item_Name__c</fullName>
        <formula>Auction_Item_Purchased__r.Auction_Item_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Auction Item Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Auction_Item_Purchased__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The auction item this opportunity has purchased.</inlineHelpText>
        <label>Auction Item Purchased</label>
        <referenceTo>Auction_Item__c</referenceTo>
        <relationshipLabel>Opportunities - Purchases</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Auction_Non_Deductible_Amount__c</fullName>
        <inlineHelpText>The portion of the opportunity amount that is not tax-deductible (fee for service or product, etc.) Leave blank, or set to $0, if the opp is fully deductible.</inlineHelpText>
        <label>Auction Non-Deductible Amount</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

src/classes/AUC_CTRL_AuctionCheckOut_TEST.cls
// Written by David Habib, copyright (c) 2009-2018 DJH Consulting, djhconsulting.com
// This program is released under the GNU Affero General Public License, Version 3. http://www.gnu.org/licenses/

@IsTest
public with sharing class AUC_CTRL_AuctionCheckOut_TEST {

	static testMethod void CodeCoverageTests() {
		// create needed data
		Account acc = new Account(Name='My Test Account');
		insert acc;
		Contact contact1 = new Contact(FirstName='David', LastName='Test', AccountId=acc.Id);
		insert contact1;
		Contact contact2 = new Contact(FirstName='John', LastName='Test', AccountId=acc.Id);
		insert contact2;

		Auction__c auction = new Auction__c (
			Name = 'Test Auction',
			Auction_Date__c = System.today()
		);
		insert auction;

		Campaign campaign = [SELECT Id, Auction__c FROM Campaign WHERE Auction_Campaign_Type__c=:AUC_AuctionConstants.CAMPAIGN_TYPE_AuctionAttendees AND Auction__c = :auction.Id];
		System.assertEquals(auction.Id, campaign.Auction__c);

		CampaignMember cm1 = new CampaignMember();
		cm1.CampaignId = campaign.Id;
		cm1.ContactId = contact1.Id;
		insert cm1;

		CampaignMember cm2 = new CampaignMember();
		cm2.CampaignId = campaign.Id;
		cm2.ContactId = contact2.Id;
		insert cm2;

		Auction_Item__c ai = new Auction_Item__c (
			Auction_Item_Name__c = 'Test Auction Item',
			Auction__c = auction.Id,
			FMV_Override__c = 100
		);
		insert ai;

		AUC_AuctionMaintenance am = new AUC_AuctionMaintenance();
		am.auctionId = auction.Id;
		System.assertEquals(campaign.Id, am.campaignIdAuctionAttendees);

		Opportunity oppPurchase= new Opportunity (
			Name = 'My Auction Item Purchase',
			CampaignId = campaign.Id,
			RecordTypeId = AUC_AuctionMaintenance.recordtypeIdAuctionPurchasedItem,
			StageName = AUC_AuctionConstants.OPP_STAGE_PLEDGED,
			CloseDate = System.today(),
			Amount = 150,
			Auction_Item_Purchased__c = ai.Id,
			Auction_Non_Deductible_Amount__c = 100
		);
		insert oppPurchase;
		System.assertEquals(150, oppPurchase.Amount);
		System.assertEquals(100, oppPurchase.Auction_Non_Deductible_Amount__c);

		Opportunity opp = [SELECT Id, Name, Auction_Deductible_Amount__c FROM Opportunity WHERE Id=:oppPurchase.Id];
		System.assertEquals(50, opp.Auction_Deductible_Amount__c);

		OpportunityContactRole oppcr = new OpportunityContactRole();
		oppcr.ContactId = contact1.Id;
		oppcr.OpportunityId = oppPurchase.Id;
		oppcr.IsPrimary = true;
		insert oppcr;

		//point to our VF page
		PageReference p = new PageReference('Page.AuctionCheckOut');
		p.getParameters().put('auctionId', auction.Id);
		Test.setCurrentPageReference(p);

		//instantiate the controller for this opp
		AUC_CTRL_AuctionCheckOut ctrl = new AUC_CTRL_AuctionCheckOut();

		System.assertEquals(auction.Id, ctrl.auctionId);
		ctrl.ChangeAuction();
		System.assertEquals(auction.Id, ctrl.auctionId);

		ctrl.searchPurchaser = '';
		ctrl.SearchPurchaserLookup();
		System.assertEquals(null, ctrl.contactIdPurchaser);
		System.assert(ctrl.strStatus.startsWith('Enter the name'));

		ctrl.searchPurchaser = 'This guy does not exist';
		ctrl.SearchPurchaserLookup();
		System.assertEquals(null, ctrl.contactIdPurchaser);
		System.assert(ctrl.strStatus.startsWith('No attendee'));

		ctrl.searchPurchaser = 'David Test';
		ctrl.SearchPurchaserLookup();
		System.assertEquals(contact1.Id, ctrl.contactIdPurchaser);
		System.assertEquals('David Test - ', ctrl.strNamePurchaser);
		System.assert(ctrl.strStatus.startsWith('1. Check <b>Pay Now</b>'));
		System.assert(ctrl.listReceipts != null);
		System.assertEquals(1, ctrl.listReceipts.size());
		System.assert(ctrl.listReceipts[0].listOppAuctionPurchases != null);
		System.assertEquals(1, ctrl.listReceipts[0].listOppAuctionPurchases.size());
		System.assertEquals(150, ctrl.listReceipts[0].decTotalAmountToPay);
		System.assert(ctrl.strOpenReceiptURL != null);
		System.assert(ctrl.strCreditCardChargeURL == null || ctrl.strCreditCardChargeURL != null);
		System.assert(ctrl.fHasReceipts);

		ctrl.oppIdChecked = oppPurchase.Id;
		ctrl.listReceipts[0].listOppAuctionPurchases[0].IsPayNow = false;
		System.assertEquals(null, ctrl.ChangePayNow());
		System.assertEquals(0, ctrl.decTotalAmountToPay);
		System.assertEquals(null, ctrl.UpdateCheckedOpps());
		System.assertEquals('You must Check off which Opportunities to update.', ctrl.strSaveResults);

		ctrl.oppIdChecked = oppPurchase.Id;
		ctrl.listReceipts[0].listOppAuctionPurchases[0].IsPayNow = true;
		System.assertEquals(null, ctrl.ChangePayNow());
		System.assertEquals(150, ctrl.decTotalAmountToPay);
		List<Id> oppIdsToPay = ctrl.getOppIdsToPay();
		System.assertEquals(1, oppIdsToPay.size());
		System.assertEquals(oppPurchase.Id, oppIdsToPay[0]);

		opp = [SELECT Id, Name, Auction_Deductible_Amount__c, StageName FROM Opportunity WHERE Id=:oppPurchase.Id];
		System.assertEquals(AUC_AuctionConstants.OPP_STAGE_PLEDGED, opp.StageName);
		System.assert(ctrl.UpdateCheckedOpps() == null);
		opp = [SELECT Id, Name, Auction_Deductible_Amount__c, StageName, Probability, ForecastCategoryName FROM Opportunity WHERE Id=:oppPurchase.Id];
		System.assertEquals(AUC_AuctionConstants.OPP_STAGE_WON_NOT_THANKED_STAGE, opp.StageName);
		System.assertEquals(AUC_AuctionConstants.oppStageWonNotThankedProbability, opp.Probability);
		System.assertEquals(AUC_AuctionConstants.oppStageWonNotThankedForecastCategoryName, opp.ForecastCategoryName);

		List<AUC_CTRL_AuctionCheckOut.Purchaser> listP = AUC_CTRL_AuctionCheckOut.getListPurchasers(auction.Id, 'Test');
		System.assert(listP != null);
		System.assertEquals(2, listP.size());

		ctrl.contactIdPurchaser = contact2.Id;
		ctrl.ChangePurchaserLookup();
		System.assert(ctrl.strStatus.contains('no purchases'));
		System.assert(ctrl.listReceipts != null);
		System.assert(ctrl.listReceipts.size() == 0); // since contact2 has no purchases.
		System.assert(ctrl.fHasReceipts == false);
		System.assert(ctrl.Close() != null);

		System.assertEquals(null, ctrl.NextGuest());
		System.assertEquals(null, ctrl.ChangePaymentMethod());
		System.assertNotEquals(null, ctrl.strPaymentProcessorWindowParameters);
		System.assertNotEquals(null, ctrl.fShowPaymentProcessorOnPage);
		System.assertNotEquals(null, ctrl.strPaymentProcessorPageHeight);
		System.assertEquals(null, ctrl.ShowPanelCreditCard());
		System.assertEquals(true, ctrl.isPaymentSettingsMissing);


	}

	static testMethod void handleNoAuction() {
		//point to our VF page
		PageReference p = new PageReference('Page.AuctionCheckOut');
		Test.setCurrentPageReference(p);

		//instantiate the controller for this opp
		AUC_CTRL_AuctionCheckOut ctrl = new AUC_CTRL_AuctionCheckOut();

		System.assertEquals(null, ctrl.auctionId);
		System.assertEquals('You must first create an Auction before using this page.', ctrl.strSaveResults);
		System.assertEquals(ctrl.strSaveResults, ctrl.strStatus);

	}
}