src/objects/Auction__c.object
<CustomObject>
    <description>The master object which is the parent of all campaigns and auction items, that represent the entire auction.</description>
    <label>Auction</label>
    <nameField>
        <label>Auction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Auctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Auction_Item__c.object
<CustomObject>
    <description>A purchaseable item at an auction, such as a weekend getaway, a food basket, a certificate for free exercise classes.</description>
    <fields>
        <fullName>Allow_Multiple_Purchases__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check if you want the Auction Purchases page to allow this item to be purchased multiple times.</inlineHelpText>
        <label>Allow Multiple Purchases</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Auction_Group__c</fullName>
        <inlineHelpText>The auction group this auction item is offered in.</inlineHelpText>
        <label>Auction Group</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Live round 1</fullName>
                </value>
                <value>
                    <fullName>Live round 2</fullName>
                </value>
                <value>
                    <fullName>Silent round 1</fullName>
                </value>
                <value>
                    <fullName>Silent round 2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Auction_Item_Name__c</fullName>
        <inlineHelpText>The short name for the auction item.</inlineHelpText>
        <label>Auction Item Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Auction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The auction this item is for.</inlineHelpText>
        <label>Auction</label>
        <referenceTo>Auction__c</referenceTo>
        <relationshipLabel>Auction Items</relationshipLabel>
        <relationshipName>Auction_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Children</fullName>
                </value>
                <value>
                    <fullName>Excursions</fullName>
                </value>
                <value>
                    <fullName>Food and Beverage</fullName>
                </value>
                <value>
                    <fullName>Home and Garden</fullName>
                </value>
                <value>
                    <fullName>Sporting</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>The full description of the item to use in the marketing of the item (booklet, placards, etc.)</inlineHelpText>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Display_Board__c</fullName>
        <inlineHelpText>Does this auction item require a display board to be created for it?</inlineHelpText>
        <label>Display Board</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>n/a</fullName>
                </value>
                <value>
                    <fullName>Required</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Donor_Recognition__c</fullName>
        <inlineHelpText>The donors that you want to recognize for this auction item in the marketing of this item.</inlineHelpText>
        <label>Donor Recognition</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>FMV_Override__c</fullName>
        <inlineHelpText>If empty, the sum of the Actual FMV&apos;s of all pieces will be used.</inlineHelpText>
        <label>FMV Override</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FMV_Rollup__c</fullName>
        <inlineHelpText>The FMV of all of the pieces added together</inlineHelpText>
        <label>FMV Rollup</label>
        <summarizedField>Auction_Item_Piece__c.Actual_FMV__c</summarizedField>
        <summaryForeignKey>Auction_Item_Piece__c.Auction_Item__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Fair_Market_Value__c</fullName>
        <formula>IF(FMV_Override__c &gt; 0, FMV_Override__c, FMV_Rollup__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The Fair Market Value of the auction item.</inlineHelpText>
        <label>Fair Market Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Guaranteed_Bid__c</fullName>
        <inlineHelpText>The amount that guarantees the bidder this auction item.</inlineHelpText>
        <label>Guaranteed Bid</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Minimum_Bid__c</fullName>
        <inlineHelpText>The minimum bid to accept for this auction item.</inlineHelpText>
        <label>Minimum Bid</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Restrictions__c</fullName>
        <inlineHelpText>Any restrictions on the donated item, like when it is not available.</inlineHelpText>
        <label>Restrictions</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Treat_Purchase_as_Gift__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If checked, create any purchase opportunity as record type &quot;Gift&quot;, not &quot;Auction Item Purchase&quot;.</inlineHelpText>
        <label>Treat Purchase as Gift</label>
        <type>Checkbox</type>
    </fields>
    <label>Auction Item</label>
    <nameField>
        <label>Auction Item ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Auction Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AUC_CTRL_AuctionItems.cls
// Written by David Habib, copyright (c) 2009-2013 DJH Consulting, djhconsulting.com 
// This program is released under the GNU Affero General Public License, Version 3. http://www.gnu.org/licenses/

public with sharing class AUC_CTRL_AuctionItems extends PageControllerBase {
    /*********C&P Code Start**********/
      public boolean paaspackage{get;set;}//Check PaaS existance 
      public  List<Auction_Item__c> Auc_Items = null; //To get Auctions Items fields
     /********C&P Code End*************/
    
    // constructor
    public AUC_CTRL_AuctionItems() {
        listStrFields = AUC_AuctionMaintenance.listStrFromFieldSet('Auction_Item__c', 'AuctionItemsTabFS');
        strNameField = listStrFields[0]; 
        strObjectType = 'Auction_Item__c';    
        
        /************C&P Code Start***************/
        /*************Check if paas Package exists or not*************/
         paaspackage= false;
         List<ApexClass> cls = [SELECT NamespacePrefix FROM ApexClass where NamespacePrefix='CnP_PaaS' Limit 1];
         if(!cls.isempty() && cls!= null){
             paaspackage= true;
         }
       /************C&P Code End***************/     
    }

    public override string getStrPageUniqueName() {
        return 'AuctionItems';
    }   
    
    public override string getStrSoql() {   
        string strSoql = 'select Id, ' + string.join(listStrFields, ',') + 
                ' from Auction_Item__c ' +
                'where Auction__c=\'' + ctrlSoqlListView.auctionId + '\''; 

        if (ctrlSoqlListView.strAlphaFilter != null) {
            strSoql += ' and Auction_Item_Name__c like \'' + ctrlSoqlListView.strAlphaFilter + '%\'';
        }                               
        return strSoql;         
    }

    public override PageReference NewItem() { 
        // ideally, we'd pass the AuctionId to the new page, but I haven't 
        // figured out how to do that in a way that works with a managed package.
        string strPrefix = Schema.getGlobalDescribe().get('Auction_Item__c').getDescribe().getKeyPrefix();
        //string strAuctionFldId = 'CF00NA0000001MnD3';  NOTE: couldn't find a way to get this at runtime!
        //list<Auction__c> listAuc = [select Id, Name from Auction__c where Id = :ctrlSoqlListView.auctionId] ;
//'/' + strPrefix + '/e?' + 
system.debug('ssssss'+strPrefix);
        PageReference p = new PageReference('/' + strPrefix + '/e?' + 
            // strAuctionFldId + '=' + (listAuc.size() > 0 ? listAuc[0].Name : '') + '&' + 
            // strAuctionFldId + '_lkid=' + ctrlSoqlListView.auctionId + 
            '&retURL=/apex/AuctionItems');
        return p;
    }
    
    public PageReference DonatedItemConverter() {
        PageReference p = new PageReference('/apex/AuctionDonatedItemConverter?auctionId=' + 
            ctrlSoqlListView.auctionId +
            '&retURL=' +
            ApexPages.currentPage().getUrl());
        return p;
    }
    /*******C&P Code Start********/
    //Navigating to AuctionItemsList page
    public ApexPages.PageReference downloadFile( ) { 
        return Page.AuctionItemsList; 
    }
    //to get fields from Auction Items object
    public List<Auction_Item__c> getAuc_Items(){
        if(Auc_Items == null){
            Auc_Items = [select Name, Allow_Multiple_Purchases__c, Auction__c, Auction_Group__c, Auction_Item_Name__c, SKU__c,Token_Value__c,Category__c,Description__c,Display_Board__c,Donor_Recognition__c,Fair_Market_Value__c,FMV_Override__c,FMV_Rollup__c,Guaranteed_Bid__c,Minimum_Bid__c,Restrictions__c,Show_Tax_Deductible__c,Total_Tax_Deductible__c,Treat_Purchase_as_Gift__c from Auction_Item__c where Auction__c=:ctrlSoqlListView.auctionId  limit 1000];
        }
        return Auc_Items;   
    }
    /*******C&P Code End********/
}