src/objects/Auction__c.object
<CustomObject>
    <description>The master object which is the parent of all campaigns and auction items, that represent the entire auction.</description>
    <fields>
        <fullName>Auction_Date__c</fullName>
        <label>Auction Date</label>
        <type>Date</type>
    </fields>
    <label>Auction</label>
    <nameField>
        <label>Auction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Auctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/AuctionSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Holds all settings used in Auctions that the user is able to modify for their organization.</description>
    <fields>
        <fullName>Allow_Duplicate_Bid_Numbers__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Whether to disable the trigger that enforces unique Bid Numbers for each attendee per Auction.      NOTE: It is recommended that only one member of a Household should be given a Bid Number, and that this setting remain unchecked.</inlineHelpText>
        <label>Allow Duplicate Bid Numbers</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact_Household_Field__c</fullName>
        <inlineHelpText>The developer name of a lookup field to households on Contacts.  If using the Non Profit Starter Pack, Auctions will automatically use npo02__Household__c.  If using Accounts for householding, specify AccountId.</inlineHelpText>
        <label>Contact Household Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Household_Name_Field__c</fullName>
        <inlineHelpText>The developer path name to the name field on households from Contact. If using the Non Profit Starter Pack, Auctions will automatically use npo02__Household__r.Name. If using Accounts for householding, specify Account.Name.</inlineHelpText>
        <label>Contact Household Name Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>AuctionSettings</label>
</CustomObject>

src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Auction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The auction this campaign is a part of.</inlineHelpText>
        <label>Auction</label>
        <referenceTo>Auction__c</referenceTo>
        <relationshipLabel>Campaigns</relationshipLabel>
        <relationshipName>Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Campaign</fullName>
        <active>true</active>
        <description>default record type required to enable installation of Auctions package</description>
        <label>Campaign</label>
    </recordTypes>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

src/classes/AUC_CTRL_AuctionAutoBidNumber_TEST.cls
// Written by David Habib, copyright (c) 2009-2018 DJH Consulting, djhconsulting.com
// This program is released under the GNU Affero General Public License, Version 3. http://www.gnu.org/licenses/

@IsTest
public with sharing class AUC_CTRL_AuctionAutoBidNumber_TEST {

	static testMethod void CodeCoverageTests() {

		// temporarily set household custom setting to hit more code coverage
		delete [SELECT Id FROM AuctionSettings__c];
		AuctionSettings__c settings = new AuctionSettings__c();
		settings.Contact_Household_Field__c = 'AccountId';
		settings.Contact_Household_Name_Field__c = 'Account.Name';
		settings.Allow_Duplicate_Bid_Numbers__c = false;
		settings.Name = 'test settings';
		insert settings;
		System.assertEquals('AccountId', AUC_AuctionConstants.strContactHouseholdField);

		// create needed data
		Account acc = new Account(Name='My Test Account for Contacts');
		insert acc;

		Integer cContact = 10;
		List<Contact> listContact = new List<Contact>();
		for (Integer i = 0; i < cContact; i++) {
			listContact.add(new Contact(FirstName='Person:' + i, LastName='Test', AccountId=acc.Id));
		}
		insert listContact;

		Auction__c auction = new Auction__c (
			Name = 'Test Auction',
			Auction_Date__c = System.today()
		);
		insert auction;

		AUC_AuctionMaintenance am = new AUC_AuctionMaintenance();
		am.auctionId = auction.Id;
		Id campaignId = am.campaignIdAuctionAttendees;

		List<CampaignMember> listCM = new List<CampaignMember>();
		for (Integer i = 0; i < cContact; i++) {
			listCM.add(new CampaignMember(CampaignId = campaignId, ContactId = listContact[i].Id));
		}
		insert listCM;

		// now test our  page
		PageReference p = new PageReference('Page.AuctionAutoBidNumbers');
		p.getParameters().put('auctionId', auction.Id);
		Test.setCurrentPageReference(p);

		//instantiate the controller for this opp
		AUC_CTRL_AuctionAutoBidNumbers ctrl = new AUC_CTRL_AuctionAutoBidNumbers();
		System.assert(ctrl.listCMBidNumbers != null);
		ctrl.fOneBidNumberPerHousehold = true;
		ctrl.AutoBidNumbersSet();
		System.assertEquals('Successfully set the Bid Number for ' + cContact + ' auction attendees.', ctrl.strAutoBidNumberResult);

		// test duplicate detection failure handling
		ctrl.listCMBidNumbers[0].iNewBidNumber = 123;
		ctrl.listCMBidNumbers[2].iNewBidNumber = 123;
		ctrl.AutoBidNumbersSet();
		System.assert(ctrl.strAutoBidNumberResult.contains('Errors occurred'));

		// also test no param scenario.
		p = new PageReference('Page.AuctionAutoBidNumbers');
		Test.setCurrentPageReference(p);
		ctrl = new AUC_CTRL_AuctionAutoBidNumbers();
		System.assertEquals('There was no AuctionId passed as a parameter to the page.', ctrl.strAutoBidNumberResult);
		ctrl.AutoBidNumbersSet();
		System.assertEquals('The specified Auction was invalid or did not have an Auction Attendees Campaign.  No bid numbers were changed.', ctrl.strAutoBidNumberResult);

		System.assert(ctrl.Cancel() != null);
	}

}