src/objects/Auction__c.object
<CustomObject>
    <description>The master object which is the parent of all campaigns and auction items, that represent the entire auction.</description>
    <fields>
        <fullName>Auction_Date__c</fullName>
        <label>Auction Date</label>
        <type>Date</type>
    </fields>
    <label>Auction</label>
    <nameField>
        <label>Auction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Auctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Auction_Campaign_Type__c</fullName>
        <label>Auction Campaign Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Auction Attendees</fullName>
                </value>
                <value>
                    <fullName>Auction Tickets</fullName>
                </value>
                <value>
                    <fullName>Auction Sponsors</fullName>
                </value>
                <value>
                    <fullName>Auction Item Donors</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Auction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The auction this campaign is a part of.</inlineHelpText>
        <label>Auction</label>
        <referenceTo>Auction__c</referenceTo>
        <relationshipLabel>Campaigns</relationshipLabel>
        <relationshipName>Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Campaign</fullName>
        <active>true</active>
        <description>default record type required to enable installation of Auctions package</description>
        <label>Campaign</label>
    </recordTypes>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

src/classes/AUC_TEST_Auction_ProtectCampaigns.cls
// Written by David Habib, copyright (c) 2009-2013 DJH Consulting, djhconsulting.com 
// This program is released under the GNU Affero General Public License, Version 3. http://www.gnu.org/licenses/

@IsTest
private with sharing class AUC_TEST_Auction_ProtectCampaigns {
	
	public static testMethod void TestCodeCoverage() {
   		// create needed data
    	Auction__c auction = new Auction__c (
			Name = 'Test Auction',
			Auction_Date__c = System.today()
		);  
		insert auction;  	
    	
    	Campaign campaign = [SELECT Id, Auction__c FROM Campaign
    		WHERE Auction_Campaign_Type__c=:AUC_AuctionConstants.CAMPAIGN_TYPE_AuctionAttendees
    			AND Auction__c = :auction.Id];
    	System.assert(campaign.Id != null);
    	System.assertEquals(auction.Id, campaign.Auction__c);
    	
		try {
			delete campaign;
			System.assert(false);
		} catch (Exception ex) {
			System.assert(ex.getMessage().contains('You must delete the Auction first'));
		}
	}
}