src/objects/Auction__c.object
<CustomObject>
    <description>The master object which is the parent of all campaigns and auction items, that represent the entire auction.</description>
    <label>Auction</label>
    <nameField>
        <label>Auction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Auctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Auction_Item__c.object
<CustomObject>
    <description>A purchaseable item at an auction, such as a weekend getaway, a food basket, a certificate for free exercise classes.</description>
    <fields>
        <fullName>Auction_Item_Name__c</fullName>
        <inlineHelpText>The short name for the auction item.</inlineHelpText>
        <label>Auction Item Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Auction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The auction this item is for.</inlineHelpText>
        <label>Auction</label>
        <referenceTo>Auction__c</referenceTo>
        <relationshipLabel>Auction Items</relationshipLabel>
        <relationshipName>Auction_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>The full description of the item to use in the marketing of the item (booklet, placards, etc.)</inlineHelpText>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Auction Item</label>
    <nameField>
        <label>Auction Item ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Auction Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Auction_Item_Piece__c.object
<CustomObject>
    <description>It&apos;s the junction table to map Donated Items to Auction Items.</description>
    <fields>
        <fullName>Actual_FMV__c</fullName>
        <description>workflow rule sets this automatically from the calculated field Estimated FMV.  This is so the master object, Auction Item, can have a Rollup Summary field on Actual FMV.  (Salesforce didn&apos;t allow the Rollup Summary field on Estimated FMV, because it uses a cross object formula).</description>
        <inlineHelpText>The actual Fair Market Value to use.</inlineHelpText>
        <label>Actual FMV</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Auction_Donated_Item_Name__c</fullName>
        <formula>Opportunity__r.Auction_Donated_Item_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Auction Donated Item Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Auction_Item__c</fullName>
        <label>Auction Item</label>
        <referenceTo>Auction_Item__c</referenceTo>
        <relationshipLabel>Auction Item Pieces</relationshipLabel>
        <relationshipName>Auction_Item_Pieces</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Estimated_FMV__c</fullName>
        <formula>(Opportunity__r.Amount / Opportunity__r.Number_of_Items__c ) * Quantity__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Automatically calculated fair market value based on the value of the opportunity and the number of items.</inlineHelpText>
        <label>Estimated FMV</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Auction Item Pieces</relationshipLabel>
        <relationshipName>Auction_Item_Pieces</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <inlineHelpText>how many of these pieces are included</inlineHelpText>
        <label>Quantity</label>
        <precision>5</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Auction Item Piece</label>
    <nameField>
        <displayFormat>AIP-{0000}</displayFormat>
        <label>Piece ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Auction Item Pieces</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Auction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The auction this campaign is a part of.</inlineHelpText>
        <label>Auction</label>
        <referenceTo>Auction__c</referenceTo>
        <relationshipLabel>Campaigns</relationshipLabel>
        <relationshipName>Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Campaign</fullName>
        <active>true</active>
        <description>default record type required to enable installation of Auctions package</description>
        <label>Campaign</label>
    </recordTypes>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Auction_Donated_Item_Name__c</fullName>
        <inlineHelpText>The short name of the donated auction item.</inlineHelpText>
        <label>Auction Donated Item Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Auction_Item_Name__c</fullName>
        <formula>Auction_Item_Purchased__r.Auction_Item_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Auction Item Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Number_Available__c</fullName>
        <formula>Number_of_Items__c - Number_Used__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Number Available</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Items__c</fullName>
        <inlineHelpText>If the Auction Donated Item is multiple items that can be auctioned, the number of items.</inlineHelpText>
        <label>Number of Items</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src/classes/AUC_CTRL_AuctionNewItemPieceWizard.cls
// Written by David Habib, copyright (c) 2009-2013 DJH Consulting, djhconsulting.com 
// This program is released under the GNU Affero General Public License, Version 3. http://www.gnu.org/licenses/

public with sharing class AUC_CTRL_AuctionNewItemPieceWizard {
	
	// public Properties	
	public Auction_Item_Piece__c aip { get; set; }			
	public Id oppDonatedItemId { get; set; } 
	public Id auctionItemId { get; set; }
	public Id auctionId { get; set; }
	

	private AUC_AuctionMaintenance auctionMaintenance;
	private ApexPages.StandardController stdController;
	private String strQueryParams;

	//constructor
	public AUC_CTRL_AuctionNewItemPieceWizard (ApexPages.StandardController controller) {

		checkFLS();

		//get record from standard controller
		stdController = controller;
        this.aip = (Auction_Item_Piece__c)controller.getRecord();

        // Keep track of any inbound query string parameters so they can be passed along when creating a new record
        List<String> pageUrl = ApexPages.currentPage().getUrl().split('\\?');
		if (pageUrl.size() > 1) {
			strQueryParams = pageUrl[1];
		}

        // we are getting called from either an Auction Item, or a Donated Item.
        // figure out which one, and then derive the auctionId.
        if (aip.Auction_Item__c != null) {
        	List<Auction_Item__c> listAI = [SELECT Auction__c FROM Auction_Item__c WHERE Id=:aip.Auction_Item__c];
        	auctionId = listAI[0].Auction__c;
        	auctionItemId = aip.Auction_Item__c;
        } 

        if (aip.Opportunity__c != null) {
        	List<Campaign> listCmp = [SELECT Auction__c FROM Campaign WHERE Id IN
        		(SELECT CampaignId FROM Opportunity WHERE Id = :aip.Opportunity__c) ];
        	auctionId = listCmp[0].Auction__c;
	        oppDonatedItemId = aip.Opportunity__c;
	        // NOTE: we correctly set the oppId, but if there are no items left for this donation,
	        // it won't appear in the picklist of donated items, and thus it will come up empty.
        } 
        			
		auctionMaintenance = new AUC_AuctionMaintenance();
		auctionMaintenance.auctionId = auctionId;
	}

	// check Field Level Security and object permissions on all objects and fields this page uses
	private void checkFLS() {
		UTIL_Describe.checkReadAccess(UTIL_Describe.StrTokenNSPrefix('Auction_Item_Piece__c'), new Set<String>{
			'Name',
			UTIL_Describe.StrTokenNSPrefix('Actual_FMV__c'),
			UTIL_Describe.StrTokenNSPrefix('Auction_Donated_Item_Name__c'),
			UTIL_Describe.StrTokenNSPrefix('Auction_Item__c'),
			UTIL_Describe.StrTokenNSPrefix('Description__c'),
			UTIL_Describe.StrTokenNSPrefix('Estimated_FMV__c'),
			UTIL_Describe.StrTokenNSPrefix('Opportunity__c'),
			UTIL_Describe.StrTokenNSPrefix('Quantity__c')
		});
	}
	
	// the list of opps to put in the Auction Donated Item dropdown
	public List<SelectOption> listSODonatedItems {
		get {
			try {
				if (listSODonatedItems == null) {
					listSODonatedItems = new List<SelectOption>();
					UTIL_Describe.checkReadAccess('Opportunity', new Set<String>{
						'Amount',
						UTIL_Describe.StrTokenNSPrefix('Auction_Donated_Item_Name__c'),
						UTIL_Describe.StrTokenNSPrefix('Number_Available__c'),
						UTIL_Describe.StrTokenNSPrefix('Number_of_Items__c')
					});
					listSODonatedItems.add(new SelectOption('', ''));
					for (Opportunity opp : [
						SELECT Auction_Donated_Item_Name__c, Id, Number_Available__c, Number_of_Items__c, Amount
						FROM Opportunity
						WHERE RecordTypeId = :AUC_AuctionMaintenance.recordtypeIdAuctionDonatedItem
						AND Number_Available__c > 0
						AND CampaignId = :auctionMaintenance.campaignIdAuctionDonors
						ORDER BY Auction_Donated_Item_Name__c DESC
						LIMIT 999
					]) {
						if (opp.Number_of_Items__c > 0) {
							Decimal cost = ((opp.Amount == null) ? 0 : opp.Amount) / opp.Number_of_Items__c;
							listSODonatedItems.add(new SelectOption(opp.Id, opp.Auction_Donated_Item_Name__c + ' ('
								+ Integer.valueOf(opp.Number_Available__c) + ' available at $'
								+ String.valueOf(cost.setScale(2)) + ' each)'));
						}
					}
				}
				return listSODonatedItems;
			} catch (Exception ex) {
				ApexPages.addMessages(ex);
				// for some reason, the addMessage doesn't work in this scenario (maybe due to it being a getter?)
				// so let's also put the error in the select list!
				listSODonatedItems.add(new SelectOption('', ex.getMessage()));
				return listSODonatedItems;
			}
		}
		private set;
	}

	// the list of Auction Items to put in the Auction Item dropdown
	public List<SelectOption> listSOAuctionItems {
		get {
			try {
				if (listSOAuctionItems == null) {
					listSOAuctionItems = new List<SelectOption>();
					UTIL_Describe.checkReadAccess(UTIL_Describe.StrTokenNSPrefix('Auction_Item__c'), new Set<String>{
						'Name',
						UTIL_Describe.StrTokenNSPrefix('Auction_Item_Name__c')
					});
					listSOAuctionItems.add(new SelectOption('', ''));
					for (Auction_Item__c ai : [
						SELECT Id, Name, Auction_Item_Name__c
						FROM Auction_Item__c
						WHERE Auction__c = :auctionId
						ORDER BY Name
						LIMIT 999
					]) {
						listSOAuctionItems.add(new SelectOption(ai.Id, ai.Name + ' - ' + ai.Auction_Item_Name__c));
					}
				}
				return listSOAuctionItems;
			} catch (Exception ex) {
				ApexPages.addMessages(ex);
				// for some reason, the addMessage doesn't work in this scenario (maybe due to it being a getter?)
				// so let's also put the error in the select list!
				listSOAuctionItems.add(new SelectOption('', ex.getMessage()));
				return listSOAuctionItems;
			}
		}
		private set;
	}

	public PageReference Save() {
		aip.Auction_Item__c = auctionItemId;
		aip.Opportunity__c = oppDonatedItemId;
		if (stdController.save() != null) {
			return new PageReference('/' + aip.Auction_Item__c);
		}
		return null;
	}
	
	public PageReference SaveAndNew() {
		if (Save() != null) {
			// there is no action method on the standard controller for New, so we must hack this.
			ApexPages.currentPage().setRedirect(true);
            return new PageReference('/' + aip.getSObjectType().getDescribe().getKeyPrefix() + '/e?' + strQueryParams);					
		}
		return null;
	}

	// under LEX, stdController.cancel didn't go back to the auction item
	// so we force it when we can.
	public PageReference Cancel() {
		ApexPages.currentPage().setRedirect(true);
		if (aip.Auction_Item__c != null) {
			return new PageReference('/' + aip.Auction_Item__c);
		}
		return stdController.cancel();
	}
}