src/objects/Auction__c.object
<CustomObject>
    <description>The master object which is the parent of all campaigns and auction items, that represent the entire auction.</description>
    <fields>
        <fullName>Auction_Date__c</fullName>
        <label>Auction Date</label>
        <type>Date</type>
    </fields>
    <label>Auction</label>
    <nameField>
        <label>Auction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Auctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Auction_Item__c.object
<CustomObject>
    <description>A purchaseable item at an auction, such as a weekend getaway, a food basket, a certificate for free exercise classes.</description>
    <fields>
        <fullName>Auction_Item_Name__c</fullName>
        <inlineHelpText>The short name for the auction item.</inlineHelpText>
        <label>Auction Item Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Auction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The auction this item is for.</inlineHelpText>
        <label>Auction</label>
        <referenceTo>Auction__c</referenceTo>
        <relationshipLabel>Auction Items</relationshipLabel>
        <relationshipName>Auction_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Auction Item</label>
    <nameField>
        <label>Auction Item ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Auction Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Auction_Campaign_Type__c</fullName>
        <label>Auction Campaign Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Auction Attendees</fullName>
                </value>
                <value>
                    <fullName>Auction Tickets</fullName>
                </value>
                <value>
                    <fullName>Auction Sponsors</fullName>
                </value>
                <value>
                    <fullName>Auction Item Donors</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Auction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The auction this campaign is a part of.</inlineHelpText>
        <label>Auction</label>
        <referenceTo>Auction__c</referenceTo>
        <relationshipLabel>Campaigns</relationshipLabel>
        <relationshipName>Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Campaign</fullName>
        <active>true</active>
        <description>default record type required to enable installation of Auctions package</description>
        <label>Campaign</label>
    </recordTypes>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

src/objects/CampaignMember.object
<CustomObject>
    <fields>
        <fullName>Bid_Number__c</fullName>
        <inlineHelpText>The attendee&apos;s Bid Number, used to identify their purchases.  It is recommended that only one person per household is given a Bid Number.</inlineHelpText>
        <label>Bid Number</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Auction_Donated_Item_Name__c</fullName>
        <inlineHelpText>The short name of the donated auction item.</inlineHelpText>
        <label>Auction Donated Item Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Auction_Item_Name__c</fullName>
        <formula>Auction_Item_Purchased__r.Auction_Item_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Auction Item Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bid_Number__c</fullName>
        <inlineHelpText>The purchaser&apos;s Bid Number at the time the purchase was recorded in the Purchases tab.</inlineHelpText>
        <label>Bid Number</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Items__c</fullName>
        <inlineHelpText>If the Auction Donated Item is multiple items that can be auctioned, the number of items.</inlineHelpText>
        <label>Number of Items</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src/classes/AUC_CTRL_AuctionDonatedItemConverter_TST.cls
// Written by David Habib, copyright (c) 2009-2018 DJH Consulting, djhconsulting.com
// This program is released under the GNU Affero General Public License, Version 3. http://www.gnu.org/licenses/

@IsTest
public with sharing class AUC_CTRL_AuctionDonatedItemConverter_TST {

	static testMethod void CodeCoverageTests() {
		// create needed data
		Auction__c auction = new Auction__c (
			Name = 'Test Auction',
			Auction_Date__c = System.today()
		);
		insert auction;

		Campaign campaign = [SELECT Id, Auction__c FROM Campaign
		WHERE Auction_Campaign_Type__c=:AUC_AuctionConstants.CAMPAIGN_TYPE_AuctionItemDonors
		AND Auction__c = :auction.Id];
		System.assertEquals(auction.Id, campaign.Auction__c);

		Account acc = new Account(Name='My Test Account');
		insert acc;

		Contact contact = new Contact(
			FirstName = 'Johnny',
			LastName = 'Test',
			AccountId = acc.Id
		);
		insert contact;

		CampaignMember campaignmember = new CampaignMember(
			CampaignId = campaign.Id,
			ContactId = contact.Id,
			Bid_Number__c = 123
		);
		insert campaignmember;

		Opportunity opp = new Opportunity(
			RecordTypeId = AUC_AuctionMaintenance.recordtypeIdAuctionDonatedItem,
			Name = 'my donated item opp',
			CampaignId = campaign.Id,
			StageName = 'Won Not Thanked',
			CloseDate = System.today(),
			Auction_Donated_Item_Name__c = 'my test auction donated item',
			Amount = 150,
			Number_of_Items__c = 5,
			Description = 'my description of the donated item'
		);
		insert opp;
		System.assert(opp.Id != null);

		//point to our VF page
		PageReference p = new PageReference('Page.AuctionDonatedItemConverter');
		p.getParameters().put('auctionId', auction.Id);
		Test.setCurrentPageReference(p);

		//instantiate the controller for this opp
		AUC_CTRL_AuctionDonatedItemConverter ctrl = new AUC_CTRL_AuctionDonatedItemConverter();

		System.assertEquals(null, ctrl.strConvertResult);
		System.assert(ctrl.listNewAuctionItem != null);
		System.assertEquals(1, ctrl.listNewAuctionItem.size());
		ctrl.listNewAuctionItem[0].isChecked = true;

		// test error handling
		ctrl.listNewAuctionItem[0].quantity = null;
		System.assertEquals(null, ctrl.Convert());
		System.assert(ctrl.strConvertResult.contains('Errors occurred'));
		ctrl.listNewAuctionItem[0].quantity = 10;
		System.assertEquals(null, ctrl.Convert());
		System.assert(ctrl.strConvertResult.contains('Errors occurred'));

		// test successful convert
		ctrl.listNewAuctionItem[0].quantity = 1;
		System.assertEquals(null, ctrl.Convert());
		System.assert(ctrl.strConvertResult.contains('1 Auction Items were created.'));

		// verify the auctionItem got correctly created!
		List<Auction_Item__c> listAI = [SELECT Id, Auction_Item_Name__c FROM Auction_Item__c WHERE Auction__c = :auction.Id];
		System.assertEquals(1, listAI.size());
		System.assertEquals('my test auction donated item', listAI[0].Auction_Item_Name__c);

		// other methods
		System.assertNotEquals(null, ctrl.Cancel());
	}
}