src/objects/Auction__c.object
<CustomObject>
    <description>The master object which is the parent of all campaigns and auction items, that represent the entire auction.</description>
    <fields>
        <fullName>Auction_Date__c</fullName>
        <label>Auction Date</label>
        <type>Date</type>
    </fields>
    <label>Auction</label>
    <nameField>
        <label>Auction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Auctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Auction_Item__c.object
<CustomObject>
    <description>A purchaseable item at an auction, such as a weekend getaway, a food basket, a certificate for free exercise classes.</description>
    <fields>
        <fullName>Auction_Item_Name__c</fullName>
        <inlineHelpText>The short name for the auction item.</inlineHelpText>
        <label>Auction Item Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Auction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The auction this item is for.</inlineHelpText>
        <label>Auction</label>
        <referenceTo>Auction__c</referenceTo>
        <relationshipLabel>Auction Items</relationshipLabel>
        <relationshipName>Auction_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FMV_Override__c</fullName>
        <inlineHelpText>If empty, the sum of the Actual FMV&apos;s of all pieces will be used.</inlineHelpText>
        <label>FMV Override</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Auction Item</label>
    <nameField>
        <label>Auction Item ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Auction Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Auction_Campaign_Type__c</fullName>
        <label>Auction Campaign Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Auction Attendees</fullName>
                </value>
                <value>
                    <fullName>Auction Tickets</fullName>
                </value>
                <value>
                    <fullName>Auction Sponsors</fullName>
                </value>
                <value>
                    <fullName>Auction Item Donors</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Auction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The auction this campaign is a part of.</inlineHelpText>
        <label>Auction</label>
        <referenceTo>Auction__c</referenceTo>
        <relationshipLabel>Campaigns</relationshipLabel>
        <relationshipName>Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Campaign</fullName>
        <active>true</active>
        <description>default record type required to enable installation of Auctions package</description>
        <label>Campaign</label>
    </recordTypes>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Auction_Item_Name__c</fullName>
        <formula>Auction_Item_Purchased__r.Auction_Item_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Auction Item Name</label>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/AUC_CTRL_AuctionPurchases_TEST.cls
// Written by David Habib, copyright (c) 2009-2018 DJH Consulting, djhconsulting.com
// This program is released under the GNU Affero General Public License, Version 3. http://www.gnu.org/licenses/

@IsTest
public with sharing class AUC_CTRL_AuctionPurchases_TEST {

	static testMethod void CodeCoverageTests() {
		// create needed data
		Auction__c auction = new Auction__c (
			Name = 'Test Auction',
			Auction_Date__c = System.today()
		);
		insert auction;

		Campaign campaign = [SELECT Id, Auction__c FROM Campaign WHERE Auction_Campaign_Type__c=:AUC_AuctionConstants.CAMPAIGN_TYPE_AuctionAttendees
		AND Auction__c = :auction.Id];
		System.assertEquals(auction.Id, campaign.Auction__c);

		Auction_Item__c ai = new Auction_Item__c (
			Auction_Item_Name__c = 'Test Auction Item',
			Auction__c = auction.Id,
			FMV_Override__c = 100
		);
		insert ai;

		AUC_AuctionMaintenance am = new AUC_AuctionMaintenance();
		am.auctionId = auction.Id;
		System.assertEquals(campaign.Id, am.campaignIdAuctionAttendees);

		Opportunity oppPurchase= new Opportunity (
			Name = 'My Auction Item Purchase',
			CampaignId = campaign.Id,
			RecordTypeId = AUC_AuctionMaintenance.recordtypeIdAuctionPurchasedItem,
			StageName = 'Won Not Thanked',
			CloseDate = System.today(),
			Amount = 150
		);
		insert oppPurchase;

		//point to our VF page
		PageReference p = new PageReference('Page.AuctionPurchases');
		p.getParameters().put('auctionId', auction.Id);
		Test.setCurrentPageReference(p);

		//instantiate the controller
		AUC_CTRL_AuctionPurchases pageCtrl = new AUC_CTRL_AuctionPurchases();
		AUC_CTRL_SoqlListView compCtrl = new AUC_CTRL_SoqlListView();
		compCtrl.pgController = pageCtrl;
		System.assert(pageCtrl.listStrFields != null);
		System.assert(pageCtrl.strNameField != null);
		pageCtrl.ctrlSoqlListView.strAlphaFilter = 'A';
		System.assert(pageCtrl.getStrSoql() != null);
		System.assert(pageCtrl.NewItem() != null);

	}
}