src/objects/Auction__c.object
<CustomObject>
    <description>The master object which is the parent of all campaigns and auction items, that represent the entire auction.</description>
    <label>Auction</label>
    <nameField>
        <label>Auction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Auctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Auction_Item__c.object
<CustomObject>
    <description>A purchaseable item at an auction, such as a weekend getaway, a food basket, a certificate for free exercise classes.</description>
    <fields>
        <fullName>Auction_Item_Name__c</fullName>
        <inlineHelpText>The short name for the auction item.</inlineHelpText>
        <label>Auction Item Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Auction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The auction this item is for.</inlineHelpText>
        <label>Auction</label>
        <referenceTo>Auction__c</referenceTo>
        <relationshipLabel>Auction Items</relationshipLabel>
        <relationshipName>Auction_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>The full description of the item to use in the marketing of the item (booklet, placards, etc.)</inlineHelpText>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Donor_Recognition__c</fullName>
        <inlineHelpText>The donors that you want to recognize for this auction item in the marketing of this item.</inlineHelpText>
        <label>Donor Recognition</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Restrictions__c</fullName>
        <inlineHelpText>Any restrictions on the donated item, like when it is not available.</inlineHelpText>
        <label>Restrictions</label>
        <type>TextArea</type>
    </fields>
    <label>Auction Item</label>
    <nameField>
        <label>Auction Item ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Auction Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Auction_Item_Piece__c.object
<CustomObject>
    <description>It&apos;s the junction table to map Donated Items to Auction Items.</description>
    <fields>
        <fullName>Actual_FMV__c</fullName>
        <description>workflow rule sets this automatically from the calculated field Estimated FMV.  This is so the master object, Auction Item, can have a Rollup Summary field on Actual FMV.  (Salesforce didn&apos;t allow the Rollup Summary field on Estimated FMV, because it uses a cross object formula).</description>
        <inlineHelpText>The actual Fair Market Value to use.</inlineHelpText>
        <label>Actual FMV</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Auction_Donated_Item_Name__c</fullName>
        <formula>Opportunity__r.Auction_Donated_Item_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Auction Donated Item Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Auction_Item__c</fullName>
        <label>Auction Item</label>
        <referenceTo>Auction_Item__c</referenceTo>
        <relationshipLabel>Auction Item Pieces</relationshipLabel>
        <relationshipName>Auction_Item_Pieces</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Auction Item Pieces</relationshipLabel>
        <relationshipName>Auction_Item_Pieces</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <inlineHelpText>how many of these pieces are included</inlineHelpText>
        <label>Quantity</label>
        <precision>5</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Auction Item Piece</label>
    <nameField>
        <displayFormat>AIP-{0000}</displayFormat>
        <label>Piece ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Auction Item Pieces</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Auction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The auction this campaign is a part of.</inlineHelpText>
        <label>Auction</label>
        <referenceTo>Auction__c</referenceTo>
        <relationshipLabel>Campaigns</relationshipLabel>
        <relationshipName>Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Campaign</fullName>
        <active>true</active>
        <description>default record type required to enable installation of Auctions package</description>
        <label>Campaign</label>
    </recordTypes>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Auction_Donated_Item_Name__c</fullName>
        <inlineHelpText>The short name of the donated auction item.</inlineHelpText>
        <label>Auction Donated Item Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Auction_Donated_Item_Restrictions__c</fullName>
        <inlineHelpText>Any restrictions on the donated item, like when it is not available.  This will get copied over to the Auction Item when it is created.</inlineHelpText>
        <label>Auction Donated Item Restrictions</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Auction_Item_Name__c</fullName>
        <formula>Auction_Item_Purchased__r.Auction_Item_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Auction Item Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Number_of_Items__c</fullName>
        <inlineHelpText>If the Auction Donated Item is multiple items that can be auctioned, the number of items.</inlineHelpText>
        <label>Number of Items</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src/classes/AUC_CTRL_AuctionNewDonatedItemWizard.cls
// Written by David Habib, copyright (c) 2009-2013 DJH Consulting, djhconsulting.com 
// This program is released under the GNU Affero General Public License, Version 3. http://www.gnu.org/licenses/

public with sharing class AUC_CTRL_AuctionNewDonatedItemWizard {
	 
	// constructor for the class
	public AUC_CTRL_AuctionNewDonatedItemWizard() {
		// get the current auction we were invoked from, and find & set the appropriate campaign.
		// NOTE: we declared auctionId as a string to avoid getting a runtime error if null 
		// was set for the parameter, which cannot be assigned to type Id.
		String auctionId = AUC_AuctionMaintenance.StrEscape(ApexPages.currentPage().getParameters().get('auctionId'));
		
		// do any initialization which is not dependent on having an auctionId
		auctionMaintenance = new AUC_AuctionMaintenance();
		auctionItem = new Auction_Item__c();
		opp = new Opportunity(RecordTypeId=AUC_AuctionMaintenance.recordtypeIdAuctionDonatedItem);
		opp.CloseDate = System.today();
		opp.Number_of_Items__c = 1;
		AUC_AuctionMaintenance.setOpportunityStageClosed(opp);
		fCreateAuctionItem = false;	
		contactRole = new OpportunityContactRole();			
		
		// handle it if we don't have an auctionId passed in.
		if (auctionId != null && auctionId != '' && auctionId != 'null') {
			auctionMaintenance.auctionId = auctionId;	
			auctionItem.Auction__c = auctionId;
			opp.CampaignId = auctionMaintenance.campaignIdAuctionDonors;
		}
		
	}

	private AUC_AuctionMaintenance auctionMaintenance;
		
	// object to hold opportunity
	public Opportunity opp { get; set; } 
	
	// we instantiate this object to get the Contact lookup field. And we also created it for the opp.
	public OpportunityContactRole contactRole { get; set; }
	
	// object to hold the auction item
	public Auction_Item__c auctionItem { get; set; }
	
	public Boolean fCreateAuctionItem { get; set; }
	public String StrFCreateAuctionItem { get { return String.valueOf(fCreateAuctionItem); }}
		
	// status string for reporting the results of saving.
    public String strSaveResults { get; set; }    
	
	// called by the page when the user checks/unchecks the Create Auction Item checkbox.		
	public PageReference ToggleCreateAuctionItem() {		
		if (fCreateAuctionItem) {
			if (auctionItem.Auction_Item_Name__c == null) auctionItem.Auction_Item_Name__c = opp.Auction_Donated_Item_Name__c;
			if (auctionItem.Description__c == null) auctionItem.Description__c = opp.Description; 
			if (auctionItem.Restrictions__c == null) auctionItem.Restrictions__c = opp.Auction_Donated_Item_Restrictions__c;
		}
		return null;
	}	

	public PageReference Cancel() {
		PageReference p = new PageReference('/apex/AuctionDonatedItems');
        p.setRedirect(true);
        return p;
	}
		
	public PageReference Save() {
	    strSaveResults = 'Starting Save...';
		
		try {
			// since we are using apex:inputField for all Opp fields, we don't need to test each field's permissions
			UTIL_Describe.checkObjectCreateAccess('Opportunity');
			UTIL_Describe.checkObjectUpdateAccess('Opportunity');
			UTIL_Describe.checkCreateAccess('CampaignMember', new Set<String> {
				'ContactId',
				'CampaignId',
				'Status'
			});
			// since we are using apex:inputField for all Auction Item fields, we don't need to test each field's permissions
			UTIL_Describe.checkObjectCreateAccess(UTIL_Describe.StrTokenNSPrefix('Auction_Item__c'));
			UTIL_Describe.checkCreateAccess(UTIL_Describe.StrTokenNSPrefix('Auction_Item_Piece__c'), new Set<String>{
				UTIL_Describe.StrTokenNSPrefix('Auction_Item__c'),
				UTIL_Describe.StrTokenNSPrefix('Opportunity__c'),
				UTIL_Describe.StrTokenNSPrefix('Quantity__c')
			});

			Contact contact = [SELECT Name, AccountId FROM Contact WHERE Id=:contactRole.ContactId];
			String strDonor = contact.Name;
			String strDonorRole = AUC_AuctionConstants.OPP_GIFT_DONOR_ROLE;
			Account org;	
			if (opp.AccountId != null) {
				org = [SELECT Name FROM Account WHERE Id=:opp.AccountId];
				strDonor = org.Name;
				strDonorRole = AUC_AuctionConstants.OPP_ORG_GIFT_DONOR_ROLE;
			} else {
				// see if we are dealing with the NonProfit Starter Pack and it is using the 1-to-1 Account model.
				// if so, we need to set the Opp's Account to make the rollups work.
				if (AUC_AuctionConstants.fSetAccountOnNewAuctionOpps) {
					opp.AccountId = contact.AccountId;
				}
			}
			opp.Name = strDonor + ' ' + String.valueOf(AUC_AuctionMaintenance.YearOfAuctionId(auctionMaintenance.auctionId)) + AUC_AuctionConstants.OPP_NAME_SUFFIX_AuctionDonatedItem;
			// can't assume opp is new, in case of later error, and then a resave.
			if (opp.Id == null) {
				AUC_AuctionMaintenance.didUpdateOppWithNPSPOCRData(opp, contactRole.ContactId);
				insert opp;
				
				// create/update the contactRole for the donor
				contactRole.OpportunityId = opp.Id;
				contactRole.Role = strDonorRole;
				contactRole.IsPrimary = true;
				AUC_AuctionMaintenance.saveOppContactRole(contactRole);

				// add the donor to the campaign
				// handle that they might already be on the campaign!
				try {
					CampaignMember cm = new CampaignMember();
					cm.ContactId = contactRole.ContactId;
					cm.CampaignId = opp.CampaignId;
	                cm.Status = 'Donated';				
					insert cm;
				} catch (Exception e) {}
			} else {
				update opp;	
			}
			
					
			if (fCreateAuctionItem) {
				if (auctionItem.Donor_Recognition__c == null) {
					auctionItem.Donor_Recognition__c = strDonor;
				}
				insert auctionItem;		
				Auction_Item_Piece__c piece = new Auction_Item_Piece__c();
				piece.Auction_Item__c = auctionItem.Id;
				piece.Opportunity__c = opp.Id;
				piece.Quantity__c = opp.Number_of_Items__c;
				if (piece.Quantity__c == null) piece.Quantity__c = 1;
				// piece.Actual_FMV__c = opp.Amount; workflow rule now sets this field automatically.
				insert piece; 
			}
					 
			PageReference p = new PageReference('/apex/AuctionDonatedItems');
	        p.setRedirect(true);
	        return p;
        
        } catch (Exception e) {
			// note that we intentionally did not use savepoint/rollback here, to avoid having
			// to recreate opp and auctionItem (since we can't clear their Id's to null).
			if (opp.Id == null) {
				strSaveResults = 'Error encountered while trying to save the auction donated item.  ';
			} else {
				strSaveResults = 'The auction donated item has been saved, but errors were encountered trying to save the related auction item.  ';
			}
            ApexPages.addMessages(e);
            return null;
        }	   
	}
}