src/objects/Auction__c.object
<CustomObject>
    <description>The master object which is the parent of all campaigns and auction items, that represent the entire auction.</description>
    <label>Auction</label>
    <nameField>
        <label>Auction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Auctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Auction_Item__c.object
<CustomObject>
    <description>A purchaseable item at an auction, such as a weekend getaway, a food basket, a certificate for free exercise classes.</description>
    <fields>
        <fullName>Auction_Item_Name__c</fullName>
        <inlineHelpText>The short name for the auction item.</inlineHelpText>
        <label>Auction Item Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Auction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The auction this item is for.</inlineHelpText>
        <label>Auction</label>
        <referenceTo>Auction__c</referenceTo>
        <relationshipLabel>Auction Items</relationshipLabel>
        <relationshipName>Auction_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>The full description of the item to use in the marketing of the item (booklet, placards, etc.)</inlineHelpText>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Restrictions__c</fullName>
        <inlineHelpText>Any restrictions on the donated item, like when it is not available.</inlineHelpText>
        <label>Restrictions</label>
        <type>TextArea</type>
    </fields>
    <label>Auction Item</label>
    <nameField>
        <label>Auction Item ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Auction Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Auction_Item_Piece__c.object
<CustomObject>
    <description>It&apos;s the junction table to map Donated Items to Auction Items.</description>
    <fields>
        <fullName>Actual_FMV__c</fullName>
        <description>workflow rule sets this automatically from the calculated field Estimated FMV.  This is so the master object, Auction Item, can have a Rollup Summary field on Actual FMV.  (Salesforce didn&apos;t allow the Rollup Summary field on Estimated FMV, because it uses a cross object formula).</description>
        <inlineHelpText>The actual Fair Market Value to use.</inlineHelpText>
        <label>Actual FMV</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Auction_Donated_Item_Name__c</fullName>
        <formula>Opportunity__r.Auction_Donated_Item_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Auction Donated Item Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Auction_Item__c</fullName>
        <label>Auction Item</label>
        <referenceTo>Auction_Item__c</referenceTo>
        <relationshipLabel>Auction Item Pieces</relationshipLabel>
        <relationshipName>Auction_Item_Pieces</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Auction Item Pieces</relationshipLabel>
        <relationshipName>Auction_Item_Pieces</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <inlineHelpText>how many of these pieces are included</inlineHelpText>
        <label>Quantity</label>
        <precision>5</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Auction Item Piece</label>
    <nameField>
        <displayFormat>AIP-{0000}</displayFormat>
        <label>Piece ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Auction Item Pieces</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Auction_Donated_Item_Name__c</fullName>
        <inlineHelpText>The short name of the donated auction item.</inlineHelpText>
        <label>Auction Donated Item Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Auction_Donated_Item_Restrictions__c</fullName>
        <inlineHelpText>Any restrictions on the donated item, like when it is not available.  This will get copied over to the Auction Item when it is created.</inlineHelpText>
        <label>Auction Donated Item Restrictions</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Auction_Item_Name__c</fullName>
        <formula>Auction_Item_Purchased__r.Auction_Item_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Auction Item Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Number_Available__c</fullName>
        <formula>Number_of_Items__c - Number_Used__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Number Available</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Items__c</fullName>
        <inlineHelpText>If the Auction Donated Item is multiple items that can be auctioned, the number of items.</inlineHelpText>
        <label>Number of Items</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src/classes/AUC_CTRL_AuctionDonatedItemConverter.cls
// Written by David Habib, copyright (c) 2009-2013 DJH Consulting, djhconsulting.com 
// This program is released under the GNU Affero General Public License, Version 3. http://www.gnu.org/licenses/

public with sharing class AUC_CTRL_AuctionDonatedItemConverter {
	
	// constructor
	public AUC_CTRL_AuctionDonatedItemConverter() {
		auctionMaintenance = new AUC_AuctionMaintenance();
		String strAuctionId = AUC_AuctionMaintenance.StrEscape(ApexPages.currentPage().getParameters().get('auctionId'));		
		if (strAuctionId != null && strAuctionId != '' && strAuctionId != 'null') {
			auctionMaintenance.auctionId = strAuctionId;
			if (listNewAuctionItem.size() == 0) strConvertResult = 'There are no more available Donated Items that need an Auction Item.';			
		} else {
			strConvertResult = 'There was no AuctionId passed as a parameter to the page.';
		}
	}

	private AUC_AuctionMaintenance auctionMaintenance;
	
	public String strConvertResult { get; set; }
	
	// wrapper class to hold an AuctionItem, Donated Item Opportunity, and a checkbox
	public class NewAuctionItem {	

		public Auction_Item__c ai { get; set; }
		public Opportunity donatedItem { get; set; }
		public Boolean isChecked { get; set; }
		public Integer quantity { get; set; }
		public Decimal FMV { get; set; }
		
		public NewAuctionItem(Auction_Item__c aiT, Opportunity donatedItemT) {
			ai = aiT;
			donatedItem = donatedItemT;
			isChecked = false;
			quantity = Integer.valueOf(donatedItemT.Number_Available__c);
			if (donatedItemT.Amount == null || donatedItemT.Number_of_Items__c == null || donatedItemT.Number_of_Items__c == 0) {
				FMV = 0;
			} else { 
				FMV = (donatedItemT.Amount / donatedItemT.Number_of_Items__c) * quantity;
			}
		}
	}
	
	// the list of new auction items that the visualforce page displays for editing
	public List<NewAuctionItem> listNewAuctionItem { 
		get {
			try {
				UTIL_Describe.checkObjectReadAccess('Opportunity');
				if (listNewAuctionItem == null) {
					listNewAuctionItem = new List<NewAuctionItem>();

					List<Opportunity> listOpp = [SELECT Id, Name, Amount, Number_of_Items__c, Number_Available__c,
						Auction_Donated_Item_Name__c, Description, Auction_Donated_Item_Restrictions__c FROM Opportunity
						WHERE CampaignId = :auctionMaintenance.campaignIdAuctionDonors AND
							RecordTypeId = :AUC_AuctionMaintenance.recordtypeIdAuctionDonatedItem AND
							Number_Available__c > 0
						ORDER BY Auction_Donated_Item_Name__c
						LIMIT :AUC_AuctionConstants.cDonatedItemConverterBatchSize];

					// cache set of already used auction item id's
					List<Auction_Item__c> listAI = [SELECT Name FROM Auction_Item__c WHERE Auction__c = :auctionMaintenance.auctionId];
					Set<String> setItemId = new Set<String>();
					for (Auction_Item__c ai : listAI) {
						setItemId.add(ai.Name);
					}
					Integer itemId = 100;

					for (Opportunity opp : listOpp) {
						Auction_Item__c ai = new Auction_Item__c();
						ai.Auction__c = auctionMaintenance.auctionId;
						ai.Auction_Item_Name__c = opp.Auction_Donated_Item_Name__c;
						ai.Description__c = opp.Description;
						ai.Restrictions__c = opp.Auction_Donated_Item_Restrictions__c;

						// generate a free auction item id
						while (setItemId.contains(String.valueOf(itemId))) itemId++;
						ai.Name = String.valueOf(itemId++);

						listNewAuctionItem.add(new NewAuctionItem(ai, opp));
					}
				}
				return listNewAuctionItem;
			} catch (Exception e) {
				ApexPages.addMessages(e);
				return new List<NewAuctionItem>();
			}
		}
		set;
	}				
	
	// list of all fieldnames for Auction Items.
	private List<String> listStrAIFields {
		get {
			if (listStrAIFields == null) {
				Map<String, Schema.SObjectField> mapS = Schema.SObjectType.Auction_Item__c.fields.getMap();
				listStrAIFields = new List<String>();
				listStrAIFields.addAll(mapS.keySet());  
			}
			return listStrAIFields;
		}
		set;
	}
	
	// so we can throw an exception with an error message	
 	private class MyException extends Exception {}
	
	// action method to create the auction items			
	public PageReference Convert() {
		List<Auction_Item__c> listAI = new List<Auction_Item__c>();
		List<Auction_Item_Piece__c> listAIP = new List<Auction_Item_Piece__c>();

		Savepoint sp = Database.setSavepoint();
		try {
			UTIL_Describe.checkObjectCreateAccess(UTIL_Describe.StrTokenNSPrefix('Auction_Item__c'));
			UTIL_Describe.checkObjectCreateAccess(UTIL_Describe.StrTokenNSPrefix('Auction_Item_Piece__c'));

			// first create the Auction Item's
			for (NewAuctionItem nai : listNewAuctionItem) {
				if (nai.isChecked) {
					// in order to handle the insert of AI's succeeding, but 
					// then a later operation causing us to rollback,
					// we have to clone the AI's so their ID won't get set
					// by the insert!
					Auction_Item__c ai = new Auction_Item__c();
					AUC_AuctionMaintenance.CloneObject(nai.ai, ai, listStrAIFields);
					listAI.add(ai);
				}
			}
			insert listAI;
			
			// now create the Auction Item Pieces
			Integer iAI = 0;
			for (NewAuctionItem nai : listNewAuctionItem) {
				if (nai.isChecked) {
					Auction_Item_Piece__c aip = new Auction_Item_Piece__c();
					aip.Auction_Item__c = listAI[iAI++].Id;
					aip.Opportunity__c = nai.donatedItem.Id;
					if (nai.quantity == null || nai.quantity <= 0) {
                		throw (new MyException(nai.ai.Auction_Item_Name__c + ': Quantity cannot be less than one.'));												
					}
					if (nai.quantity > nai.donatedItem.Number_Available__c) {
                		throw (new MyException(nai.ai.Auction_Item_Name__c + 
                			': Quantity cannot be more than the number available (' + nai.donatedItem.Number_Available__c + ').'));						
					}
					aip.Quantity__c = nai.quantity;
					if (nai.donatedItem.Amount == null || nai.donatedItem.Number_of_Items__c == null) {
						aip.Actual_FMV__c = 0;
					} else {
						aip.Actual_FMV__c = (nai.donatedItem.Amount / nai.donatedItem.Number_of_Items__c) * aip.Quantity__c;
					}
					listAIP.add(aip);
				}
			}
			insert listAIP;
			
			strConvertResult = listAIP.size() + ' Auction Items were created.  The list has been refreshed to show remaining Donated Items.';
			listNewAuctionItem = null;
        } catch (Exception e) {
        	// undo our partially saved state
        	Database.rollback(sp);        				
			strConvertResult = 'Errors occurred: ';
            ApexPages.addMessages(e);            
        }

		return null;
	}

	// cancel the page and return to our caller. 
	public PageReference Cancel() {
		String retURL = ApexPages.currentPage().getParameters().get('retURL');
		if (retURL == null || retURL == '') {
			retURL = '/apex/GW_Auctions__AuctionItems';
		}
		PageReference p = new PageReference(retURL);
        p.setRedirect(true);
        return p;
        
	}
}