src/objects/Auction__c.object
<CustomObject>
    <description>The master object which is the parent of all campaigns and auction items, that represent the entire auction.</description>
    <fields>
        <fullName>Auction_Date__c</fullName>
        <label>Auction Date</label>
        <type>Date</type>
    </fields>
    <label>Auction</label>
    <nameField>
        <label>Auction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Auctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Auction_Item__c.object
<CustomObject>
    <description>A purchaseable item at an auction, such as a weekend getaway, a food basket, a certificate for free exercise classes.</description>
    <fields>
        <fullName>Auction_Item_Name__c</fullName>
        <inlineHelpText>The short name for the auction item.</inlineHelpText>
        <label>Auction Item Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Auction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The auction this item is for.</inlineHelpText>
        <label>Auction</label>
        <referenceTo>Auction__c</referenceTo>
        <relationshipLabel>Auction Items</relationshipLabel>
        <relationshipName>Auction_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Auction Item</label>
    <nameField>
        <label>Auction Item ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Auction Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Auction_Item_Piece__c.object
<CustomObject>
    <description>It&apos;s the junction table to map Donated Items to Auction Items.</description>
    <fields>
        <fullName>Actual_FMV__c</fullName>
        <description>workflow rule sets this automatically from the calculated field Estimated FMV.  This is so the master object, Auction Item, can have a Rollup Summary field on Actual FMV.  (Salesforce didn&apos;t allow the Rollup Summary field on Estimated FMV, because it uses a cross object formula).</description>
        <inlineHelpText>The actual Fair Market Value to use.</inlineHelpText>
        <label>Actual FMV</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Auction_Donated_Item_Name__c</fullName>
        <formula>Opportunity__r.Auction_Donated_Item_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Auction Donated Item Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Auction_Item__c</fullName>
        <label>Auction Item</label>
        <referenceTo>Auction_Item__c</referenceTo>
        <relationshipLabel>Auction Item Pieces</relationshipLabel>
        <relationshipName>Auction_Item_Pieces</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Auction Item Pieces</relationshipLabel>
        <relationshipName>Auction_Item_Pieces</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <inlineHelpText>how many of these pieces are included</inlineHelpText>
        <label>Quantity</label>
        <precision>5</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Auction Item Piece</label>
    <nameField>
        <displayFormat>AIP-{0000}</displayFormat>
        <label>Piece ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Auction Item Pieces</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Auction_Campaign_Type__c</fullName>
        <label>Auction Campaign Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Auction Attendees</fullName>
                </value>
                <value>
                    <fullName>Auction Tickets</fullName>
                </value>
                <value>
                    <fullName>Auction Sponsors</fullName>
                </value>
                <value>
                    <fullName>Auction Item Donors</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Auction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The auction this campaign is a part of.</inlineHelpText>
        <label>Auction</label>
        <referenceTo>Auction__c</referenceTo>
        <relationshipLabel>Campaigns</relationshipLabel>
        <relationshipName>Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Campaign</fullName>
        <active>true</active>
        <description>default record type required to enable installation of Auctions package</description>
        <label>Campaign</label>
    </recordTypes>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Auction_Donated_Item_Name__c</fullName>
        <inlineHelpText>The short name of the donated auction item.</inlineHelpText>
        <label>Auction Donated Item Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Auction_Item_Name__c</fullName>
        <formula>Auction_Item_Purchased__r.Auction_Item_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Auction Item Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Number_of_Items__c</fullName>
        <inlineHelpText>If the Auction Donated Item is multiple items that can be auctioned, the number of items.</inlineHelpText>
        <label>Number of Items</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src/classes/AUC_CTRL_AuctionNewItemPieceWizard_TEST.cls
// Written by David Habib, copyright (c) 2009-2018 DJH Consulting, djhconsulting.com
// This program is released under the GNU Affero General Public License, Version 3. http://www.gnu.org/licenses/

@IsTest
public with sharing class AUC_CTRL_AuctionNewItemPieceWizard_TEST {

	static testMethod void TestCodeCoverage() {

		// create needed data
		Auction__c auction = new Auction__c (
			Name = 'Test Auction',
			Auction_Date__c = System.today()
		);
		insert auction;

		Campaign campaign = [SELECT Id, Auction__c FROM Campaign
		WHERE Auction_Campaign_Type__c=:AUC_AuctionConstants.CAMPAIGN_TYPE_AuctionItemDonors
		AND Auction__c = :auction.Id];
		System.assertEquals(auction.Id, campaign.Auction__c);

		Auction_Item__c auctionitem = new Auction_Item__c (
			Auction_Item_Name__c = 'Test Auction item',
			Auction__c = auction.Id
		);
		insert auctionitem;

		Opportunity oppDonatedItem = new Opportunity (
			Amount = 100,
			Auction_Donated_Item_Name__c = 'Test Donated Item',
			CampaignId = campaign.Id,
			Name = 'Test Donated Item Opportunity',
			Number_of_Items__c = 10,
			RecordTypeId = AUC_AuctionMaintenance.recordtypeIdAuctionDonatedItem,
			StageName = 'CLOSED WON',
			CloseDate = System.today()
		);
		insert oppDonatedItem;

		//point to our VF page
		Test.setCurrentPage(new PageReference('Page.AuctionNewItemPieceWizard'));

		// create the AIP and set it up
		Auction_Item_Piece__c aip = new Auction_Item_Piece__c();
		aip.Auction_Item__c = auctionitem.Id;
		aip.Opportunity__c = oppDonatedItem.Id;

		//pass AIP into the controller
		ApexPages.StandardController sc = new ApexPages.StandardController(aip);

		//pass the controller into the extension
		AUC_CTRL_AuctionNewItemPieceWizard ext = new AUC_CTRL_AuctionNewItemPieceWizard(sc);

		System.assertEquals(auction.Id, ext.auctionId);
		System.assertEquals(auctionitem.Id, ext.auctionItemId);
		System.assertEquals(oppDonatedItem.Id, ext.oppDonatedItemId);
		System.assertEquals(2, ext.listSOAuctionItems.size());	// 2 because of the empty entry
		System.assertEquals(2, ext.listSODonatedItems.size());  // 2 because of the empty entry
		ext.aip.Quantity__c = 1;
		ext.aip.Actual_FMV__c = 10;
		System.assertNotEquals(null, ext.Save());
		System.assertNotEquals(null, ext.SaveAndNew());
		System.assertNotEquals(null, ext.Cancel());

	}
}